# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21e5f0f2bb26b6e09d4c76854795637eac83b580589f2ac264de41499fd6756be0c67d2bd9816f9d0684f8e75d654429b39b26981d153eef22b727cd20799fe4

test:
  secret_key_base: 322206408c74194aafa64a9de8b41661c34b2e9df47f5683fa6916571c59488997d097b87a2a6306653b330a1e699f560e9daa8bf7ec498cf9fc30ca2517de97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
